import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWithNavbar from "./components/LayoutWithNavbar";
import SessionWrapper from "@/app/services/sessionWrapper";
import { AuthProvider } from "./services/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Computech Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <AuthProvider>
            <LayoutWithNavbar>{children}</LayoutWithNavbar>
          </AuthProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
